### ISSUE TITLE
Separating main and dev dependencies

### ISSUE THREAD

**Issue by astraszab** [StanislavYatsevich/Store_Sales#1]
The main dependency group should only include libraries that are required for end users of the package to run the code. Do we actually need all the libraries that are currently listed under [tool.poetry.dependencies] in pyproject.toml to be in the main group?

Ref: https://realpython.com/dependency-management-python-poetry/#group-dependencies-and-add-extras

**Comment by StanislavYatsevich** [comment]
> The main dependency group should only include libraries that are required for end users of the package to run the code. Do we actually need all the libraries that are currently listed under [tool.poetry.dependencies] in pyproject.toml to be in the main group?
> 
> Ref: https://realpython.com/dependency-management-python-poetry/#group-dependencies-and-add-extras

a04bd6d246056790a8702d5b1ff70defb4d953c1
