### ISSUE TITLE
How do I run Streamlit application?

### ISSUE THREAD

**Issue by astraszab** [StanislavYatsevich/Store_Sales#3]
I'd like to run a Streamlit application locally, as I see it's implemented in src/store_sales/streamlit_app.py
Would you mind adding some details about how I can do it to README.md?

**Comment by StanislavYatsevich** [comment]
> I'd like to run a Streamlit application locally, as I see it's implemented in src/store_sales/streamlit_app.py Would you mind adding some details about how I can do it to README.md?

https://github.com/StanislavYatsevich/Store_Sales/commit/626e38e08edeadeb04e35675dadebaf359409f11 and https://github.com/StanislavYatsevich/Store_Sales/commit/bd69fe6756615d03f03dc0951e3343dc5e2f0de6
