### ISSUE TITLE
Purpose of adding_features and split_and_prepare scripts?

### ISSUE THREAD

**Issue by astraszab** [StanislavYatsevich/Store_Sales#4]
I see adding_features and split_and_prepare scripts are designed as click commands. What do these scripts do? Should I run them locally? If yes, then how and in which order? Please add some info about them to README to clarify this. 

Also it's a good practice to document individual scripts, modules, or even classes and functions, especially if they are for end users. Please review the following and make changes where you think it improves readability: https://realpython.com/documenting-python-code/

For better code style, would it make sense to make scripts' names consistent by using the same verb form? (add, split, prepare or adding, splitting, preparing)

**Comment by StanislavYatsevich** [comment]
> I see adding_features and split_and_prepare scripts are designed as click commands. What do these scripts do? Should I run them locally? If yes, then how and in which order? Please add some info about them to README to clarify this.
> 
> Also it's a good practice to document individual scripts, modules, or even classes and functions, especially if they are for end users. Please review the following and make changes where you think it improves readability: https://realpython.com/documenting-python-code/
> 
> For better code style, would it make sense to make scripts' names consistent by using the same verb form? (add, split, prepare or adding, splitting, preparing)

https://github.com/StanislavYatsevich/Store_Sales/commit/1034989bdee6a950adc3e5e5c8d84debccac4970
