### ISSUE TITLE
Downloading the data

### ISSUE THREAD

**Issue by astraszab** [StanislavYatsevich/Store_Sales#5]
https://github.com/StanislavYatsevich/Store_Sales/blob/29e25693b941653d592edbd11e2a45ab4d626282/README.md?plain=1#L24

I see there are multiple .csv files under the link. Should I download them all? Where exactly should I put them locally for the code to work? 
Please clarify in readme

**Comment by StanislavYatsevich** [comment]
> https://github.com/StanislavYatsevich/Store_Sales/blob/29e25693b941653d592edbd11e2a45ab4d626282/README.md?plain=1#L24
> 
> I see there are multiple .csv files under the link. Should I download them all? Where exactly should I put them locally for the code to work? Please clarify in readme

https://github.com/StanislavYatsevich/Store_Sales/commit/1034989bdee6a950adc3e5e5c8d84debccac4970
