### ISSUE TITLE
Error when the folder provided in --prepared_data_folder_path does not exist

### ISSUE THREAD

**Issue by astraszab** [StanislavYatsevich/Store_Sales#9]
https://github.com/StanislavYatsevich/Store_Sales/blob/9c10a6aec4c0ceecd40d976e48cf62c6d8003f37/src/store_sales/splitting_and_preparing_data.py#L19-L24

As I see from the click.option decorator, the interface allows for prepared_data_folder_path to be non-existent at the time of the command execution (there's no check for existence). However, the implementation below produces an error when the folder does not exist on the user's file system.

**Comment by StanislavYatsevich** [comment]
> https://github.com/StanislavYatsevich/Store_Sales/blob/9c10a6aec4c0ceecd40d976e48cf62c6d8003f37/src/store_sales/splitting_and_preparing_data.py#L19-L24
> 
> As I see from the click.option decorator, the interface allows for prepared_data_folder_path to be non-existent at the time of the command execution (there's no check for existence). However, the implementation below produces an error when the folder does not exist on the user's file system.

That's a good point, thanks. Added a mkdir() function that creates the folder path if it hasn't been created yet.
3c24b26
